---
- name: Pull and Run docker image of pavan996/spefrontend
  hosts: all
  tasks:
    - name: Pull pavan996/spefrontend
      docker_image:
        name: pavan996/spefrontend
        source: pull

    # - name: Create default containers
    #   docker_container:
    #     name: spefrontend
    #     image: pavan996/spefrontend
    #     state: present
    #     ports:
    #       - "3000:3000"
